[CI] Add approval workflow (#10)

diff --git a/.github/workflows/Codestyle-Check.yml b/.github/workflows/Codestyle-Check.yml
--- a/.github/workflows/Codestyle-Check.yml
+++ b/.github/workflows/Codestyle-Check.yml
@@ -1,4 +1,4 @@
-name: Codestyle-Check
+name: Codestyle
 
 on:
   pull_request:
@@ -47,6 +47,18 @@ jobs:
           pip install pre-commit==2.17.0 cpplint==1.6.0  clang-format==13.0.0
 
       - name: Check pre-commit
+        id: pre-commit
         if: steps.check-bypass.outputs.can-skip != 'true'
+        continue-on-error: true
         run: |
           pre-commit run --all-files
+
+      - name: Failure message
+        if: steps.pre-commit.outcome == 'failure'
+        run: |
+          echo "::error::Codestyle check failed."
+          echo "::error::Please install pre-commit and run the following commands locally to fix the issues:"
+          echo "::error::"
+          echo "::error::    pip install pre-commit==2.17.0  cpplint==1.6.0  clang-format==13.0.0"
+          echo "::error::    pre-commit run --all-files"
+          exit 1
